services:
  backend:
    image: visvirideveloper/nombredelproyecto-back:latest
    ports:
      - "3000:3000"
    restart: always
  
  db:
    image: visvirideveloper/nombredelproyecto-db:latest
    ports:
      - "3306:3306"
    restart: always

  frontend:
    image: visvirideveloper/nombredelproyecto-front:latest
    ports:
      - "8080:80"
    restart: always
